# Generated by Django 5.0.7 on 2024-11-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone_number1_customuser_phone_number2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('secretary', 'Secretary'), ('zonal_head', 'Zonal Fellowship Head'), ('member', 'member')], default='member', max_length=20),
        ),
    ]
